# Site settings
title: Clare Szabo's Blog 
email: ce_szabo@swbell.net
description: > # this means to ignore newlines until "baseurl:"
  I’m a graphic designer, aspiring photographer and coffee lover. 
  This is my journey through the confusing world of code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: cszabo503
github_username:  cszabo503

# Build settings
markdown: kramdown
